export {default as Hero} from "./hero/Hero.jsx"
export {default as NavBar} from "./navbar/NavBar.jsx"
export {default as Course} from "./courses/Course.jsx"
export {default as About} from "./about/About.jsx"
export {default as Services} from "./services/Services.jsx"
export {default as Contact} from "./contact/Contact.jsx"
export {default as Footer} from "./footer/Footer.jsx"
